#!/usr/bin/env python3
"""Generate the bundled demo song, its chart and the drum hit sounds.

Everything is synthesised with numpy so the repository does not need any
third-party audio.  Run again after editing to regenerate:

    python tools/make_demo_assets.py
"""

from __future__ import annotations

import shutil
import subprocess
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "game" / "data"
RATE = 44100
BPM = 128.0
BEAT = 60.0 / BPM


def write_wav(path: Path, samples: np.ndarray) -> None:
    samples = np.clip(samples, -1.0, 1.0)
    with wave.open(str(path), "wb") as fh:
        fh.setnchannels(1)
        fh.setsampwidth(2)
        fh.setframerate(RATE)
        fh.writeframes((samples * 32767).astype(np.int16).tobytes())


def envelope(length: int, attack: float, decay: float) -> np.ndarray:
    t = np.arange(length) / RATE
    return np.minimum(t / attack, 1.0) * np.exp(-t / decay)


def don_sound() -> np.ndarray:
    t = np.arange(int(RATE * 0.35)) / RATE
    pitch = 150.0 * np.exp(-t * 12.0) + 70.0
    tone = np.sin(2 * np.pi * np.cumsum(pitch) / RATE)
    thump = np.random.default_rng(1).normal(0, 1, t.size) * np.exp(-t * 60.0) * 0.4
    return (tone * envelope(t.size, 0.002, 0.12) + thump) * 0.9


def ka_sound() -> np.ndarray:
    t = np.arange(int(RATE * 0.2)) / RATE
    noise = np.random.default_rng(2).normal(0, 1, t.size)
    click = np.sin(2 * np.pi * 1800 * t) * 0.5 + np.sin(2 * np.pi * 2600 * t) * 0.3
    return (noise * 0.5 + click) * envelope(t.size, 0.001, 0.04) * 0.8


def pop_sound() -> np.ndarray:
    t = np.arange(int(RATE * 0.3)) / RATE
    return np.sin(2 * np.pi * (600 + 400 * np.exp(-t * 20)) * t) * envelope(t.size, 0.002, 0.08)


def kick(length: int) -> np.ndarray:
    t = np.arange(length) / RATE
    return np.sin(2 * np.pi * np.cumsum(120 * np.exp(-t * 20) + 45) / RATE) * envelope(length, 0.002, 0.1)


def snare(length: int) -> np.ndarray:
    t = np.arange(length) / RATE
    noise = np.random.default_rng(3).normal(0, 1, length)
    return (noise * 0.6 + np.sin(2 * np.pi * 190 * t) * 0.4) * envelope(length, 0.001, 0.07)


def hat(length: int) -> np.ndarray:
    noise = np.random.default_rng(4).normal(0, 1, length)
    return noise * envelope(length, 0.001, 0.02) * 0.35


def pluck(freq: float, length: int) -> np.ndarray:
    t = np.arange(length) / RATE
    wave_ = np.sign(np.sin(2 * np.pi * freq * t)) * 0.3 + np.sin(2 * np.pi * freq * t) * 0.7
    return wave_ * envelope(length, 0.005, 0.18) * 0.35


# Chart: 32 bars.  Each string is one bar of 16th notes (TJA digits).
BARS = [
    "0000000000000000", "0000000000000000",                       # 2 bars of intro
    "1000100010001000", "1000100011001000", "1000100010001000", "1010101020002000",
    "1000200010002000", "1000200011002000", "1000200010002000", "1122112211221122",
    "3000000030000000", "1010200010102000", "4000000040000000", "2020100020201000",
    "1000100010001000", "1000200010002000", "1122100011221000", "5000000000000080",
    "1000100010001000", "1010200010102000", "1000100010001000", "7000000000000080",
    "1122112211221122", "1212121212121212", "1111222211112222", "3000400030004000",
    "1000100010001000", "1000200010002000", "1000100010001000", "6000000000000080",
    "3000000000000000", "0000000000000000",
]
GOGO_START_BAR = 22
GOGO_END_BAR = 30
MELODY = [220, 262, 330, 262, 196, 262, 330, 392]


def render_song() -> np.ndarray:
    bars = len(BARS)
    total = int(RATE * BEAT * 4 * bars) + RATE
    mix = np.zeros(total)
    sixteenth = BEAT / 4

    def add(sound: np.ndarray, at: float, gain: float = 1.0) -> None:
        start = int(at * RATE)
        end = min(total, start + sound.size)
        mix[start:end] += sound[: end - start] * gain

    kick_s, snare_s, hat_s = kick(int(RATE * 0.25)), snare(int(RATE * 0.2)), hat(int(RATE * 0.08))
    for bar in range(2, bars - 1):
        base = bar * BEAT * 4
        for beat in range(4):
            add(kick_s, base + beat * BEAT, 0.9)
            add(hat_s, base + beat * BEAT + BEAT / 2, 0.6)
            if beat in (1, 3):
                add(snare_s, base + beat * BEAT, 0.7)
        for step in range(8):
            freq = MELODY[(step + bar) % len(MELODY)] * (2 if GOGO_START_BAR <= bar < GOGO_END_BAR else 1)
            add(pluck(freq, int(RATE * 0.3)), base + step * sixteenth * 2, 0.5)
    for bar in range(0, 2):   # count-in clicks
        for beat in range(4):
            add(hat_s, bar * BEAT * 4 + beat * BEAT, 0.8)
    return mix / max(1.0, np.abs(mix).max()) * 0.9


def write_chart(path: Path) -> None:
    lines = [
        "// TaikoEX demo chart - generated by tools/make_demo_assets.py",
        "TITLE:TaikoEX Demo",
        "SUBTITLE:--built-in test song",
        f"BPM:{BPM:g}",
        "WAVE:demo.ogg",
        "OFFSET:0",
        "DEMOSTART:15",
        "SONGVOL:100",
        "SEVOL:100",
        "",
        "COURSE:Oni",
        "LEVEL:5",
        "BALLOON:6",
        "",
        "#START",
    ]
    for index, bar in enumerate(BARS):
        if index == GOGO_START_BAR:
            lines.append("#GOGOSTART")
        if index == GOGO_END_BAR:
            lines.append("#GOGOEND")
        lines.append(bar + ",")
    lines += ["#END", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def encode_ogg(wav_path: Path, ogg_path: Path) -> bool:
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        try:
            import imageio_ffmpeg
            ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
        except ImportError:
            return False
    result = subprocess.run([ffmpeg, "-y", "-loglevel", "error", "-i", str(wav_path), "-c:a", "libvorbis", "-q:a", "5", str(ogg_path)])
    return result.returncode == 0


def main() -> None:
    sounds = DATA / "sounds"
    sounds.mkdir(parents=True, exist_ok=True)
    write_wav(sounds / "don.wav", don_sound())
    write_wav(sounds / "ka.wav", ka_sound())
    write_wav(sounds / "balloon_pop.wav", pop_sound())

    demo = DATA / "songs" / "demo"
    demo.mkdir(parents=True, exist_ok=True)
    wav_path = demo / "demo.wav"
    write_wav(wav_path, render_song())
    write_chart(demo / "demo.tja")
    if encode_ogg(wav_path, demo / "demo.ogg"):
        wav_path.unlink()
    else:
        (demo / "demo.tja").write_text((demo / "demo.tja").read_text().replace("WAVE:demo.ogg", "WAVE:demo.wav"))
        print("ffmpeg not found - kept demo.wav instead of demo.ogg")
    print("demo assets written to", DATA)


if __name__ == "__main__":
    main()
